// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Noof.Ledger.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Noof.Ledger.Persistence.Migrations
{
    [DbContext(typeof(LedgerDbContext))]
    [Migration("20261008175124_AddFxRates")]
    partial class AddFxRates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Noof.Ledger.Domain.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("app_user", "public");
                });

            modelBuilder.Entity("Noof.Ledger.Domain.BalanceCheck", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.Property<decimal>("ComputedBefore")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("computed_before");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("wallet_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Stated", "Noof.Ledger.Domain.BalanceCheck.Stated#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("numeric(19,4)")
                                .HasColumnName("stated_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");
                        });

                    b.HasKey("TransactionId");

                    b.HasIndex("WalletId");

                    b.ToTable("balance_checks", "public");
                });

            modelBuilder.Entity("Noof.Ledger.Domain.CategorizationJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset?>("ClaimedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("claimed_at");

                    b.Property<string>("ClaimedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("claimed_by");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Instruction")
                        .HasColumnType("text")
                        .HasColumnName("instruction");

                    b.Property<DateOnly?>("InstructionDay")
                        .HasColumnType("date")
                        .HasColumnName("instruction_day");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("RunAfter")
                        .HasColumnType("timestamptz")
                        .HasColumnName("run_after");

                    b.Property<int?>("SourceMessageId")
                        .HasColumnType("integer")
                        .HasColumnName("source_message_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<string>("VoiceFileId")
                        .HasColumnType("text")
                        .HasColumnName("voice_file_id");

                    b.HasKey("Id");

                    b.HasIndex("Status", "RunAfter");

                    b.HasIndex("TransactionId", "SourceMessageId", "Kind")
                        .IsUnique()
                        .HasDatabaseName("IX_categorization_jobs_transaction_id_source_message_id_kind")
                        .HasFilter("source_message_id IS NOT NULL");

                    b.ToTable("categorization_jobs", "public", t =>
                        {
                            t.HasCheckConstraint("ck_categorization_jobs_correction_has_instruction", "kind <> 1 OR instruction IS NOT NULL");

                            t.HasCheckConstraint("ck_categorization_jobs_transcription_has_voice_file", "kind <> 3 OR voice_file_id IS NOT NULL");
                        });
                });

            modelBuilder.Entity("Noof.Ledger.Domain.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name_en");

                    b.Property<string>("NameRu")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name_ru");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("categories", "public");
                });

            modelBuilder.Entity("Noof.Ledger.Domain.Charge", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<decimal>("ChargedAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("charged_amount");

                    b.Property<decimal>("FeeAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("fee_amount");

                    b.Property<decimal?>("FeeFixed")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("fee_fixed");

                    b.Property<decimal?>("FeeMinimum")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("fee_minimum");

                    b.Property<decimal?>("FeePercent")
                        .HasPrecision(9, 4)
                        .HasColumnType("numeric(9,4)")
                        .HasColumnName("fee_percent");

                    b.Property<decimal>("RateUsed")
                        .HasPrecision(24, 12)
                        .HasColumnType("numeric(24,12)")
                        .HasColumnName("rate_used");

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("source");

                    b.HasKey("TransactionId", "Currency");

                    b.ToTable("charges", "public", t =>
                        {
                            t.HasCheckConstraint("ck_charges_amounts", "charged_amount > 0 AND fee_amount >= 0 AND rate_used > 0");
                        });
                });

            modelBuilder.Entity("Noof.Ledger.Domain.Entry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("wallet_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Amount", "Noof.Ledger.Domain.Entry.Amount#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("numeric(19,4)")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");
                        });

                    b.HasKey("Id");

                    b.HasIndex("TransactionId");

                    b.HasIndex("WalletId")
                        .HasDatabaseName("ix_entries_wallet_id");

                    b.ToTable("entries", "public");
                });

            modelBuilder.Entity("Noof.Ledger.Domain.LineItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CategorizedBy")
                        .HasColumnType("integer")
                        .HasColumnName("categorized_by");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<Guid?>("MerchantId")
                        .HasColumnType("uuid")
                        .HasColumnName("merchant_id");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<Guid?>("ReceiptLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("receipt_line_id");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Amount", "Noof.Ledger.Domain.LineItem.Amount#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("numeric(19,4)")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("MerchantId");

                    b.HasIndex("ReceiptLineId");

                    b.HasIndex("TransactionId");

                    b.ToTable("line_items", "public");
                });

            modelBuilder.Entity("Noof.Ledger.Domain.Merchant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<string>("TaxId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("tax_id");

                    b.HasKey("Id");

                    b.HasIndex("TaxId")
                        .IsUnique()
                        .HasDatabaseName("ix_merchants_tax_id")
                        .HasFilter("tax_id IS NOT NULL");

                    b.ToTable("merchants", "public");
                });

            modelBuilder.Entity("Noof.Ledger.Domain.MerchantAlias", b =>
                {
                    b.Property<string>("Folded")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("folded");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid")
                        .HasColumnName("merchant_id");

                    b.HasKey("Folded");

                    b.HasIndex("MerchantId");

                    b.ToTable("merchant_aliases", "public");
                });

            modelBuilder.Entity("Noof.Ledger.Domain.Receipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("FiscalNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("fiscal_number");

                    b.Property<DateTimeOffset?>("IssuedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("issued_at");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("receipt_kind");

                    b.Property<string>("LocationName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("location_name");

                    b.Property<int?>("PaymentMethod")
                        .HasColumnType("integer")
                        .HasColumnName("payment_method");

                    b.Property<decimal?>("QrTotal")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("qr_total");

                    b.Property<string>("SellerAddress")
                        .HasColumnType("text")
                        .HasColumnName("seller_address");

                    b.Property<string>("SellerName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("seller_name");

                    b.Property<string>("SellerTaxId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("seller_tax_id");

                    b.Property<string>("SlipNumber")
                        .HasColumnType("text")
                        .HasColumnName("slip_number");

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("source");

                    b.Property<string>("TelegramFileId")
                        .HasColumnType("text")
                        .HasColumnName("telegram_file_id");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.Property<string>("VerificationUrl")
                        .HasColumnType("text")
                        .HasColumnName("verification_url");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Total", "Noof.Ledger.Domain.Receipt.Total#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("numeric(19,4)")
                                .HasColumnName("total");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");
                        });

                    b.HasKey("Id");

                    b.HasIndex("TransactionId")
                        .IsUnique();

                    b.HasIndex("SellerTaxId", "FiscalNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_receipts_seller_tax_id_fiscal_number")
                        .HasFilter("seller_tax_id IS NOT NULL AND fiscal_number IS NOT NULL");

                    b.HasIndex("SellerTaxId", "SlipNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_receipts_seller_tax_id_slip_number")
                        .HasFilter("receipt_kind = 6 AND seller_tax_id IS NOT NULL AND slip_number IS NOT NULL");

                    b.ToTable("receipts", "public");
                });

            modelBuilder.Entity("Noof.Ledger.Domain.ReceiptExchange", b =>
                {
                    b.Property<Guid>("ReceiptId")
                        .HasColumnType("uuid")
                        .HasColumnName("receipt_id");

                    b.Property<decimal?>("CommissionAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("commission_amount");

                    b.Property<string>("CommissionCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("commission_currency");

                    b.Property<decimal?>("GivenAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("given_amount");

                    b.Property<string>("GivenCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("given_currency");

                    b.Property<decimal?>("Rate")
                        .HasPrecision(24, 12)
                        .HasColumnType("numeric(24,12)")
                        .HasColumnName("rate");

                    b.Property<decimal?>("ReceivedAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("received_amount");

                    b.Property<string>("ReceivedCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("received_currency");

                    b.Property<string>("SlipNumber")
                        .HasColumnType("text")
                        .HasColumnName("slip_number");

                    b.HasKey("ReceiptId");

                    b.ToTable("receipt_exchanges", "public");
                });

            modelBuilder.Entity("Noof.Ledger.Domain.ReceiptLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("name");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("quantity");

                    b.Property<Guid>("ReceiptId")
                        .HasColumnType("uuid")
                        .HasColumnName("receipt_id");

                    b.Property<string>("TaxLabel")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("tax_label");

                    b.Property<decimal>("Total")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("total");

                    b.Property<string>("Unit")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("unit");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.HasIndex("ReceiptId", "Ordinal")
                        .IsUnique();

                    b.ToTable("receipt_lines", "public");
                });

            modelBuilder.Entity("Noof.Ledger.Domain.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("BotMessageId")
                        .HasColumnType("integer")
                        .HasColumnName("bot_message_id");

                    b.Property<int>("CaptureKind")
                        .HasColumnType("integer")
                        .HasColumnName("capture_kind");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<int>("FailureReason")
                        .HasColumnType("integer")
                        .HasColumnName("failure_reason");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<DateOnly>("OccurredOn")
                        .HasColumnType("date")
                        .HasColumnName("occurred_on");

                    b.Property<int?>("PromptMessageId")
                        .HasColumnType("integer")
                        .HasColumnName("prompt_message_id");

                    b.Property<string>("RawText")
                        .HasColumnType("text")
                        .HasColumnName("raw_text");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<long?>("TelegramChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_chat_id");

                    b.Property<string>("TelegramFileId")
                        .HasColumnType("text")
                        .HasColumnName("telegram_file_id");

                    b.Property<int?>("TelegramMessageId")
                        .HasColumnType("integer")
                        .HasColumnName("telegram_message_id");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("time_zone_id");

                    b.Property<string>("VerificationUrl")
                        .HasColumnType("text")
                        .HasColumnName("verification_url");

                    b.Property<int?>("VoiceDurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("voice_duration_seconds");

                    b.Property<string>("VoiceFileId")
                        .HasColumnType("text")
                        .HasColumnName("voice_file_id");

                    b.Property<Guid?>("WalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("wallet_id");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.HasIndex("TelegramChatId", "TelegramMessageId")
                        .IsUnique()
                        .HasFilter("telegram_chat_id IS NOT NULL");

                    b.ToTable("transactions", "public", t =>
                        {
                            t.HasCheckConstraint("ck_transactions_capture_has_content", "(capture_kind IN (0, 2) AND raw_text IS NOT NULL) OR (capture_kind = 1 AND voice_file_id IS NOT NULL) OR (capture_kind = 3 AND ((telegram_file_id IS NOT NULL) <> (verification_url IS NOT NULL)))");

                            t.HasCheckConstraint("ck_transactions_telegram_ids_match_capture_kind", "(capture_kind = 2 AND telegram_chat_id IS NULL AND telegram_message_id IS NULL) OR (capture_kind <> 2 AND telegram_chat_id IS NOT NULL AND telegram_message_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Noof.Ledger.Domain.Transfer", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.Property<int?>("FeeLeg")
                        .HasColumnType("integer")
                        .HasColumnName("fee_leg");

                    b.Property<Guid>("FromWalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_wallet_id");

                    b.Property<decimal?>("StatedRate")
                        .HasPrecision(24, 12)
                        .HasColumnType("numeric(24,12)")
                        .HasColumnName("stated_rate");

                    b.Property<string>("StatedRateBase")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("stated_rate_base");

                    b.Property<Guid>("ToWalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_wallet_id");

                    b.Property<Guid?>("VenueMerchantId")
                        .HasColumnType("uuid")
                        .HasColumnName("venue_merchant_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "From", "Noof.Ledger.Domain.Transfer.From#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("numeric(19,4)")
                                .HasColumnName("from_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("from_currency");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "To", "Noof.Ledger.Domain.Transfer.To#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("numeric(19,4)")
                                .HasColumnName("to_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("to_currency");
                        });

                    b.HasKey("TransactionId");

                    b.HasIndex("FromWalletId")
                        .HasDatabaseName("ix_transfers_from_wallet_id");

                    b.HasIndex("ToWalletId")
                        .HasDatabaseName("ix_transfers_to_wallet_id");

                    b.HasIndex("VenueMerchantId");

                    b.ToTable("transfers", "public", t =>
                        {
                            t.HasCheckConstraint("ck_transfers_amounts_positive", "from_amount > 0 AND to_amount > 0");

                            t.HasCheckConstraint("ck_transfers_stated_rate_has_base", "(stated_rate IS NULL) = (stated_rate_base IS NULL)");

                            t.HasCheckConstraint("ck_transfers_wallets_differ", "from_wallet_id <> to_wallet_id");
                        });
                });

            modelBuilder.Entity("Noof.Ledger.Domain.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<string[]>("Aliases")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("aliases")
                        .HasDefaultValueSql("'{}'");

                    b.Property<bool>("Archived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("archived");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<int?>("DefaultForPayment")
                        .HasColumnType("integer")
                        .HasColumnName("default_for_payment");

                    b.Property<bool>("IsDefaultForCurrency")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default_for_currency");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Currency")
                        .IsUnique()
                        .HasDatabaseName("ix_wallets_one_default_per_currency")
                        .HasFilter("is_default_for_currency");

                    b.HasIndex("DefaultForPayment", "Currency")
                        .IsUnique()
                        .HasDatabaseName("ix_wallets_one_default_per_payment_method_and_currency")
                        .HasFilter("default_for_payment IS NOT NULL");

                    b.ToTable("wallets", "public");
                });

            modelBuilder.Entity("Noof.Ledger.Domain.WalletFxTerms", b =>
                {
                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("wallet_id");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<decimal?>("FeeFixed")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("fee_fixed");

                    b.Property<decimal?>("FeeMinimum")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("fee_minimum");

                    b.Property<decimal?>("FeePercent")
                        .HasPrecision(9, 4)
                        .HasColumnType("numeric(9,4)")
                        .HasColumnName("fee_percent");

                    b.Property<decimal>("Rate")
                        .HasPrecision(24, 12)
                        .HasColumnType("numeric(24,12)")
                        .HasColumnName("rate");

                    b.HasKey("WalletId", "Currency");

                    b.ToTable("wallet_fx_terms", "public", t =>
                        {
                            t.HasCheckConstraint("ck_wallet_fx_terms_rate_positive", "rate > 0");
                        });
                });

            modelBuilder.Entity("Noof.Ledger.Persistence.Backup.BackupRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("FileName")
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<DateTimeOffset>("FinishedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("finished_at");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("started_at");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("boolean")
                        .HasColumnName("succeeded");

                    b.HasKey("Id");

                    b.ToTable("backup_runs", "public");
                });

            modelBuilder.Entity("Noof.Ledger.Persistence.BugReports.BugReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("closed_at");

                    b.Property<string>("CollectionFailures")
                        .HasColumnType("text")
                        .HasColumnName("collection_failures");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("DeliveredAs")
                        .HasColumnType("text")
                        .HasColumnName("delivered_as");

                    b.Property<string>("Explanation")
                        .HasColumnType("text")
                        .HasColumnName("explanation");

                    b.Property<int>("ExplanationAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("explanation_attempts");

                    b.Property<DateTimeOffset>("ExplanationNextAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("explanation_next_at");

                    b.Property<int>("ExplanationState")
                        .HasColumnType("integer")
                        .HasColumnName("explanation_state");

                    b.Property<string>("FindingsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("findings");

                    b.Property<string>("LogLinesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("log_lines");

                    b.Property<bool?>("LooksLikeBug")
                        .HasColumnType("boolean")
                        .HasColumnName("looks_like_bug");

                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Number"));

                    b.Property<string>("RecordSummary")
                        .HasColumnType("text")
                        .HasColumnName("record_summary");

                    b.Property<string>("ReplyTo")
                        .HasColumnType("text")
                        .HasColumnName("reply_to");

                    b.Property<DateTimeOffset?>("SnapshotAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("snapshot_at");

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("source");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Text")
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<Guid?>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.HasIndex("TransactionId");

                    b.HasIndex("Source", "ReplyTo")
                        .IsUnique()
                        .HasDatabaseName("IX_bug_reports_source_reply_to")
                        .HasFilter("reply_to IS NOT NULL");

                    b.ToTable("bug_reports", "public", t =>
                        {
                            t.HasCheckConstraint("ck_bug_reports_closed_at_matches_status", "status <> 0 AND (status = 2) = (closed_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_bug_reports_explanation_matches_state", "explanation_state <> 0 AND (explanation_state = 2) = (explanation IS NOT NULL AND looks_like_bug IS NOT NULL)");

                            t.HasCheckConstraint("ck_bug_reports_source_and_reply_to", "source <> 0 AND (delivered_as IS NULL OR reply_to IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Noof.Ledger.Persistence.Diagnostics.AppLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Exception")
                        .HasColumnType("text")
                        .HasColumnName("exception");

                    b.Property<short>("Level")
                        .HasColumnType("smallint")
                        .HasColumnName("level");

                    b.Property<DateTimeOffset>("LoggedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("logged_at");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("PropertiesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("properties");

                    b.Property<string>("Source")
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("Template")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("template");

                    b.Property<Guid?>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.HasKey("Id");

                    b.HasIndex("LoggedAt");

                    b.HasIndex("TransactionId");

                    b.HasIndex("Level", "LoggedAt");

                    b.ToTable("app_log", "public");
                });

            modelBuilder.Entity("Noof.Ledger.Persistence.Fx.FxRateRow", b =>
                {
                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<DateOnly>("AsOfDate")
                        .HasColumnType("date")
                        .HasColumnName("as_of_date");

                    b.Property<string>("Source")
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("fetched_at");

                    b.Property<decimal>("UnitsPerEur")
                        .HasPrecision(24, 12)
                        .HasColumnType("numeric(24,12)")
                        .HasColumnName("units_per_eur");

                    b.HasKey("Currency", "AsOfDate", "Source");

                    b.ToTable("fx_rates", "public", t =>
                        {
                            t.HasCheckConstraint("ck_fx_rates_currency_not_eur", "currency <> 'EUR'");

                            t.HasCheckConstraint("ck_fx_rates_units_per_eur_positive", "units_per_eur > 0");
                        });
                });

            modelBuilder.Entity("Noof.Ledger.Persistence.Revisions.TransactionRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Instruction")
                        .HasColumnType("text")
                        .HasColumnName("instruction");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("revision_number");

                    b.Property<string>("Snapshot")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("snapshot");

                    b.Property<int>("StatusAfter")
                        .HasColumnType("integer")
                        .HasColumnName("status_after");

                    b.Property<int>("StatusBefore")
                        .HasColumnType("integer")
                        .HasColumnName("status_before");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId", "RevisionNumber")
                        .IsUnique();

                    b.ToTable("transaction_revisions", "public");
                });

            modelBuilder.Entity("Noof.Ledger.Persistence.Secrets.AppSecret", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("Ciphertext")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ciphertext");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Key");

                    b.ToTable("app_secret", "public");
                });

            modelBuilder.Entity("Noof.Ledger.Persistence.Settings.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("app_setting", "public");
                });

            modelBuilder.Entity("Noof.Ledger.Domain.BalanceCheck", b =>
                {
                    b.HasOne("Noof.Ledger.Domain.Transaction", null)
                        .WithOne()
                        .HasForeignKey("Noof.Ledger.Domain.BalanceCheck", "TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Noof.Ledger.Domain.Wallet", null)
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Noof.Ledger.Domain.CategorizationJob", b =>
                {
                    b.HasOne("Noof.Ledger.Domain.Transaction", null)
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Noof.Ledger.Domain.Category", b =>
                {
                    b.HasOne("Noof.Ledger.Domain.Category", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Noof.Ledger.Domain.Charge", b =>
                {
                    b.HasOne("Noof.Ledger.Domain.Transaction", null)
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Noof.Ledger.Domain.Entry", b =>
                {
                    b.HasOne("Noof.Ledger.Domain.Transaction", null)
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Noof.Ledger.Domain.Wallet", null)
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Noof.Ledger.Domain.LineItem", b =>
                {
                    b.HasOne("Noof.Ledger.Domain.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Noof.Ledger.Domain.Merchant", null)
                        .WithMany()
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Noof.Ledger.Domain.ReceiptLine", null)
                        .WithMany()
                        .HasForeignKey("ReceiptLineId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Noof.Ledger.Domain.Transaction", null)
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Noof.Ledger.Domain.MerchantAlias", b =>
                {
                    b.HasOne("Noof.Ledger.Domain.Merchant", null)
                        .WithMany()
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Noof.Ledger.Domain.Receipt", b =>
                {
                    b.HasOne("Noof.Ledger.Domain.Transaction", null)
                        .WithOne()
                        .HasForeignKey("Noof.Ledger.Domain.Receipt", "TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Noof.Ledger.Domain.ReceiptExchange", b =>
                {
                    b.HasOne("Noof.Ledger.Domain.Receipt", null)
                        .WithOne()
                        .HasForeignKey("Noof.Ledger.Domain.ReceiptExchange", "ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Noof.Ledger.Domain.ReceiptLine", b =>
                {
                    b.HasOne("Noof.Ledger.Domain.Receipt", null)
                        .WithMany()
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Noof.Ledger.Domain.Transaction", b =>
                {
                    b.HasOne("Noof.Ledger.Domain.Wallet", null)
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Noof.Ledger.Domain.Transfer", b =>
                {
                    b.HasOne("Noof.Ledger.Domain.Wallet", null)
                        .WithMany()
                        .HasForeignKey("FromWalletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Noof.Ledger.Domain.Wallet", null)
                        .WithMany()
                        .HasForeignKey("ToWalletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Noof.Ledger.Domain.Transaction", null)
                        .WithOne()
                        .HasForeignKey("Noof.Ledger.Domain.Transfer", "TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Noof.Ledger.Domain.Merchant", null)
                        .WithMany()
                        .HasForeignKey("VenueMerchantId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Noof.Ledger.Domain.WalletFxTerms", b =>
                {
                    b.HasOne("Noof.Ledger.Domain.Wallet", null)
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Noof.Ledger.Persistence.BugReports.BugReport", b =>
                {
                    b.HasOne("Noof.Ledger.Domain.Transaction", null)
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Noof.Ledger.Persistence.Revisions.TransactionRevision", b =>
                {
                    b.HasOne("Noof.Ledger.Domain.Transaction", null)
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
