// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Noof.Ledger.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Noof.Ledger.Persistence.Migrations;

[DbContext(typeof(LedgerDbContext))]
partial class LedgerDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("public")
            .HasAnnotation("ProductVersion", "10.0.12")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Noof.Ledger.Persistence.MoneyProbeEntity", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<DateTimeOffset>("RecordedAt")
                    .HasColumnType("timestamptz")
                    .HasColumnName("recorded_at");

                b.ComplexProperty(typeof(Dictionary<string, object>), "Amount", "Noof.Ledger.Persistence.MoneyProbeEntity.Amount#Money", b1 =>
                    {
                        b1.IsRequired();

                        b1.Property<decimal>("Amount")
                            .HasPrecision(19, 4)
                            .HasColumnType("numeric(19,4)")
                            .HasColumnName("amount");

                        b1.Property<string>("Currency")
                            .IsRequired()
                            .HasMaxLength(3)
                            .HasColumnType("character varying(3)")
                            .HasColumnName("currency");
                    });

                b.HasKey("Id");

                b.ToTable("money_probe_entities", "public");
            });
#pragma warning restore 612, 618
    }
}
