using System.Text;

namespace Noof.Ledger.Demo.Shots;

internal static class Gallery
{
    public static string Render(IReadOnlyList<AppScreen> screens, IReadOnlyList<ChatScene> scenes)
    {
        var markdown = new StringBuilder();
        Line(markdown, "# Screenshots");
        Line(markdown, "");
        Line(markdown, "Generated by `.\\run.ps1 screenshots` from the demo database's mock data (`tools/Noof.Ledger.Demo`).");
        Line(markdown, "Do not edit by hand; a change to what the app shows regenerates them.");
        Line(markdown, "");
        Line(markdown, "## App");

        foreach (var screen in screens)
        {
            Line(markdown, "");
            Line(markdown, $"### {screen.Title}");
            Line(markdown, "");
            Line(markdown, $"""<img src="app/{screen.Name}-desktop.png" width="640" alt="{screen.Title}, desktop"> <img src="app/{screen.Name}-phone.png" width="200" alt="{screen.Title}, phone">""");
        }

        Line(markdown, "");
        Line(markdown, "## Telegram");

        foreach (var scene in scenes)
        {
            Line(markdown, "");
            Line(markdown, $"### {scene.Title}");
            Line(markdown, "");
            Line(markdown, $"""<img src="telegram/{scene.Name}.png" width="300" alt="{scene.Title}">""");
        }

        return markdown.ToString();
    }

    static void Line(StringBuilder markdown, string text) => markdown.Append(text).Append('\n');
}
