<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Noof.Ledger.Demo.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Playwright" />
    <PackageReference Include="System.Drawing.Common" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Noof.Ledger.Host\Noof.Ledger.Host.csproj" />
  </ItemGroup>

</Project>
