using System.Text.Json;
using System.Text.Json.Nodes;
using Microsoft.Extensions.AI;

namespace Noof.Ledger.Ai;

// A tool declared from a hand-built JSON Schema rather than one generated by reflection.
// Declaration-only: FunctionInvokingChatClient cannot invoke it, so a call to it ends the loop and
// comes back to the caller, which is how record_transaction's answer is read.
internal sealed class SchemaTool(string name, string description, JsonElement schema) : AIFunctionDeclaration
{
    public override string Name => name;

    public override string Description => description;

    public override JsonElement JsonSchema => schema;

    public override IReadOnlyDictionary<string, object?> AdditionalProperties { get; } = StrictTool.Marker();
}

// The invocable counterpart: FunctionInvokingChatClient calls it and sends its answer back to the model.
internal sealed class SchemaFunction(string name, string description, JsonElement schema, Func<object?> answer) : AIFunction
{
    public override string Name => name;

    public override string Description => description;

    public override JsonElement JsonSchema => schema;

    public override IReadOnlyDictionary<string, object?> AdditionalProperties { get; } = StrictTool.Marker();

    protected override ValueTask<object?> InvokeCoreAsync(AIFunctionArguments arguments, CancellationToken cancellationToken) =>
        ValueTask.FromResult(answer());
}

// Every schema this assembly declares has "additionalProperties": false and every property in
// "required", so every tool is strict: the model's arguments must match the schema exactly. This
// says so without naming a provider; each provider's client translates it into its own wire format.
internal static class StrictTool
{
    const string PropertyName = "noof.strict";

    public static AdditionalPropertiesDictionary Marker() => new() { [PropertyName] = true };

    public static bool IsStrict(this AITool tool) =>
        tool.AdditionalProperties.TryGetValue(PropertyName, out var strict) && strict is true;
}

// An anyOf, not "type": ["string", "null"] beside the enum: the Anthropic API checks every enum
// value against the type array as a whole and rejects the tool with a 400 ("Enum value 'EUR' does
// not match declared type '['string', 'null']'", fixed in 4161444 for record_transaction). Every
// nullable string enum in every strict schema this assembly declares goes through this instead.
internal static class NullableEnum
{
    public static JsonObject String(IEnumerable<string> values, string description) => new()
    {
        ["anyOf"] = new JsonArray(
            new JsonObject { ["type"] = "string", ["enum"] = new JsonArray([.. values.Select(value => (JsonNode)value)]) },
            new JsonObject { ["type"] = "null" }),
        ["description"] = description,
    };
}

// The object counterpart of NullableEnum, and an anyOf for the same reason: each branch keeps one type, so the
// strict validator checks the object branch's "additionalProperties": false and its full "required" list on their
// own. Every property is required (absent values are null), derived from the properties given, as the line item does.
internal static class NullableObject
{
    public static JsonObject Of(string description, params (string Name, JsonNode Schema)[] properties) => new()
    {
        ["anyOf"] = new JsonArray(
            new JsonObject
            {
                ["type"] = "object",
                ["additionalProperties"] = false,
                ["required"] = new JsonArray([.. properties.Select(property => (JsonNode)property.Name)]),
                ["properties"] = new JsonObject(
                    properties.Select(property => KeyValuePair.Create(property.Name, (JsonNode?)property.Schema))),
            },
            new JsonObject { ["type"] = "null" }),
        ["description"] = description,
    };
}
