using System.Text.Json;
using Microsoft.Extensions.AI;

namespace Noof.Ledger.Ai;

// A tool declared from a hand-built JSON Schema rather than one generated by reflection.
// Declaration-only: FunctionInvokingChatClient cannot invoke it, so a call to it ends the loop and
// comes back to the caller, which is how record_spending's answer is read.
internal sealed class SchemaTool(string name, string description, JsonElement schema) : AIFunctionDeclaration
{
    public override string Name => name;

    public override string Description => description;

    public override JsonElement JsonSchema => schema;

    public override IReadOnlyDictionary<string, object?> AdditionalProperties { get; } = StrictTool.Marker();
}

// The invocable counterpart: FunctionInvokingChatClient calls it and sends its answer back to the model.
internal sealed class SchemaFunction(string name, string description, JsonElement schema, Func<object?> answer) : AIFunction
{
    public override string Name => name;

    public override string Description => description;

    public override JsonElement JsonSchema => schema;

    public override IReadOnlyDictionary<string, object?> AdditionalProperties { get; } = StrictTool.Marker();

    protected override ValueTask<object?> InvokeCoreAsync(AIFunctionArguments arguments, CancellationToken cancellationToken) =>
        ValueTask.FromResult(answer());
}

// Every schema this assembly declares has "additionalProperties": false and every property in
// "required", so every tool is strict: the model's arguments must match the schema exactly. This
// says so without naming a provider; each provider's client translates it into its own wire format.
internal static class StrictTool
{
    const string PropertyName = "noof.strict";

    public static AdditionalPropertiesDictionary Marker() => new() { [PropertyName] = true };

    public static bool IsStrict(this AITool tool) =>
        tool.AdditionalProperties.TryGetValue(PropertyName, out var strict) && strict is true;
}
