CREATE TABLE public.app_user (
    id uuid NOT NULL,
    username character varying(64) NOT NULL,
    password_hash text NOT NULL,
    created_at timestamptz NOT NULL,
    CONSTRAINT "PK_app_user" PRIMARY KEY (id)
);


CREATE TABLE public.money_probe_entities (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    recorded_at timestamptz NOT NULL,
    amount numeric(19,4) NOT NULL,
    currency character varying(3) NOT NULL,
    CONSTRAINT "PK_money_probe_entities" PRIMARY KEY (id)
);
