<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Noof.Ledger.Application\Noof.Ledger.Application.csproj" />
    <ProjectReference Include="..\Noof.Ledger.Domain\Noof.Ledger.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Noof.Ledger.Persistence.Tests" />
    <InternalsVisibleTo Include="Noof.Ledger.Host.Tests" />
    <InternalsVisibleTo Include="Noof.Ledger.E2E.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.Abstractions" />
  </ItemGroup>

</Project>
